name: Setup NATS Server
description: Install and cache NATS Server binary

inputs:
    version:
        description: "NATS Server version (e.g., latest, v2.10.29, v2.11.8)"
        required: false
        default: "latest"

runs:
    using: composite
    steps:
        - name: Cache NATS Server
          uses: actions/cache@v4
          id: cache-nats
          with:
              path: ~/nats-server
              key: nats-server-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

        - name: Install NATS Server
          if: steps.cache-nats.outputs.cache-hit != 'true'
          shell: bash
          run: |
              INSTALL_DIR="$HOME/nats-server"
              mkdir -p "$INSTALL_DIR"
              curl -fsSL https://binaries.nats.dev/nats-io/nats-server/v2@${{ inputs.version }} | PREFIX="$INSTALL_DIR" sh

        - name: Add NATS Server to PATH
          shell: bash
          run: echo "$HOME/nats-server" >> $GITHUB_PATH

        - name: Verify NATS Server
          shell: bash
          run: nats-server -v
